#!/bin/bash
# Script to install ShortcutHelper as a systemd user service

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
SERVICE_NAME="shortcut-helper.service"
SERVICE_FILE="$PROJECT_DIR/$SERVICE_NAME"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}📦 Installing ShortcutHelper as a systemd service...${NC}"

# Check if virtual environment exists
if [ ! -d "$PROJECT_DIR/venv" ]; then
    echo -e "${RED}❌ Virtual environment not found!${NC}"
    echo "Run first: ./setup.sh"
    exit 1
fi

# Check if shortcut_helper.py exists
if [ ! -f "$PROJECT_DIR/shortcut_helper.py" ]; then
    echo -e "${RED}❌ shortcut_helper.py not found!${NC}"
    exit 1
fi

# Get the current user
CURRENT_USER=$(whoami)
PYTHON_PATH="$PROJECT_DIR/venv/bin/python"
SCRIPT_PATH="$PROJECT_DIR/shortcut_helper.py"

# Detect the display (try to get from current session or default to :0)
DETECTED_DISPLAY="${DISPLAY:-:0}"
if [ -z "$DISPLAY" ]; then
    # Try to detect from who command
    WHO_DISPLAY=$(who | grep -E "$CURRENT_USER.*\(:" | head -1 | awk '{print $2}' | cut -d: -f2)
    if [ -n "$WHO_DISPLAY" ]; then
        DETECTED_DISPLAY=":$WHO_DISPLAY"
    fi
fi

echo -e "${YELLOW}Detected DISPLAY: $DETECTED_DISPLAY${NC}"

# Create systemd user directory if it doesn't exist
mkdir -p "$SYSTEMD_USER_DIR"

# Create the service file
echo -e "${YELLOW}Creating systemd service file...${NC}"
# This file is auto-generated by install-service.sh
# It uses absolute paths detected at installation time
# Use %h for home directory (systemd specifier)
cat > "$SERVICE_FILE" << EOF
# Auto-generated by install-service.sh
# Do not edit manually - paths are detected dynamically at installation time
[Unit]
Description=ShortcutHelper - Keyboard shortcuts popup helper
After=graphical-session.target
PartOf=graphical-session.target

[Service]
Type=simple
Environment="DISPLAY=$DETECTED_DISPLAY"
Environment="XAUTHORITY=%h/.Xauthority"
WorkingDirectory=$PROJECT_DIR
ExecStart=$PYTHON_PATH $SCRIPT_PATH
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

# Copy service file to systemd user directory
echo -e "${YELLOW}Installing service to $SYSTEMD_USER_DIR...${NC}"
cp "$SERVICE_FILE" "$SYSTEMD_USER_DIR/"

# Reload systemd daemon
echo -e "${YELLOW}Reloading systemd daemon...${NC}"
systemctl --user daemon-reload

# Enable the service
echo -e "${YELLOW}Enabling service to start on boot...${NC}"
systemctl --user enable "$SERVICE_NAME"

# Start the service
echo -e "${YELLOW}Starting service...${NC}"
systemctl --user start "$SERVICE_NAME"

# Check status
sleep 2
if systemctl --user is-active --quiet "$SERVICE_NAME"; then
    echo -e "${GREEN}✅ ShortcutHelper service installed and started successfully!${NC}"
    echo ""
    echo "Useful commands:"
    echo "  Status:  systemctl --user status $SERVICE_NAME"
    echo "  Stop:    systemctl --user stop $SERVICE_NAME"
    echo "  Start:   systemctl --user start $SERVICE_NAME"
    echo "  Restart: systemctl --user restart $SERVICE_NAME"
    echo "  Logs:    journalctl --user -u $SERVICE_NAME -f"
else
    echo -e "${RED}❌ Service failed to start. Check logs with:${NC}"
    echo "  journalctl --user -u $SERVICE_NAME -n 50"
    exit 1
fi
